services:
  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - app
    networks:
      - public
    restart: always
  app:
    build: ./spring-chat-app/
    container_name: spring_chat_app
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      - ACTIVE_PROFILE=default
      - DATABASE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - private
      - public
    restart: always
  db:
    image: postgres:17.6
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - private
    restart: always

networks:
  private:
  public:

volumes:
  db_data:
